---
- name: Test playbook
  hosts: localhost
  connection: local
  gather_facts: yes
  collections:
    - redhat.openshift
    - redhat.openshift_virtualization

  tasks:
  
  - name: Set vars
    ansible.builtin.debug:
      msg: "Hello from AAP"

